// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Util = require("./Util.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function guard(x, y) {
  if ((x + y | 0) === 2020) {
    return x !== y;
  } else {
    return false;
  }
}

var IntFindable = {
  guard: guard
};

var IntTwoCombFinder = Util.MakeTwoCombsFinder(IntFindable);

function findSolution(l) {
  return Belt_Option.map(Belt_Array.get(Curry._1(IntTwoCombFinder.find, l), 0), (function (param) {
                return Math.imul(param[0], param[1]);
              }));
}

var readStr = Fs.readFileSync("./res/day1.txt", "utf8");

var splitted = readStr.split("\n");

var numArrays = Belt_Array.map(splitted, (function (x) {
        return Belt_Option.getExn(Belt_Int.fromString(x));
      }));

var ans = findSolution(numArrays);

console.log(ans);

function findP2Solution(l) {
  var match = Belt_List.getExn(Belt_List.keep(Belt_List.flatten(Belt_List.flatten(Belt_List.map(l, (function (x0) {
                          return Belt_List.map(l, (function (x1) {
                                        return Belt_List.map(l, (function (x2) {
                                                      return [
                                                              x0,
                                                              x1,
                                                              x2
                                                            ];
                                                    }));
                                      }));
                        })))), (function (p) {
              var x2 = p[2];
              var x1 = p[1];
              var x0 = p[0];
              if (x0 !== x1 && x1 !== x2 && x0 !== x2) {
                return ((x0 + x1 | 0) + x2 | 0) === 2020;
              } else {
                return false;
              }
            })), 0);
  return Math.imul(Math.imul(match[0], match[1]), match[2]);
}

var numList = Belt_List.fromArray(numArrays);

var arrs = findP2Solution(numList);

console.log(arrs);

var budget_list = {
  hd: 1721,
  tl: {
    hd: 979,
    tl: {
      hd: 366,
      tl: {
        hd: 299,
        tl: {
          hd: 675,
          tl: {
            hd: 1456,
            tl: /* [] */0
          }
        }
      }
    }
  }
};

exports.budget_list = budget_list;
exports.IntFindable = IntFindable;
exports.IntTwoCombFinder = IntTwoCombFinder;
exports.findSolution = findSolution;
exports.readStr = readStr;
exports.splitted = splitted;
exports.numArrays = numArrays;
exports.ans = ans;
exports.findP2Solution = findP2Solution;
exports.numList = numList;
exports.arrs = arrs;
/* IntTwoCombFinder Not a pure module */
