// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Map = require("bs-platform/lib/js/belt_Map.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Range = require("bs-platform/lib/js/belt_Range.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var mapInputs = Fs.readFileSync("res/day11.txt", "utf8").split("\n");

var width = Belt_Option.mapWithDefault(Belt_Array.get(mapInputs, 0), 0, (function (w) {
        return w.length;
      }));

var height = mapInputs.length;

function seatId(p) {
  return Math.imul(p.x, width) + p.y | 0;
}

function cmp(a, b) {
  return seatId(a) - seatId(b) | 0;
}

var PointCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

function charToObj($$char) {
  switch ($$char) {
    case "#" :
        return /* Occupied */0;
    case "." :
        return /* Floor */2;
    case "L" :
        return /* Empty */1;
    default:
      return ;
  }
}

function objToChar(obj) {
  switch (obj) {
    case /* Occupied */0 :
        return "#";
    case /* Empty */1 :
        return "L";
    case /* Floor */2 :
        return ".";
    
  }
}

function initialize(param) {
  var initialMap = Belt_Map.make(PointCmp);
  return Belt_Array.reduceWithIndex(mapInputs, initialMap, (function (m, row, yi) {
                return Belt_Array.reduceWithIndex(Belt_Array.keepMap(Array.from(row, (function (x) {
                                      return x;
                                    })), charToObj), m, (function (m, cell, xi) {
                              return Belt_Map.set(m, {
                                          x: xi,
                                          y: yi
                                        }, cell);
                            }));
              }));
}

function adjacentSeats(c, seatingMap) {
  return Belt_Map.keep(seatingMap, (function (p, param) {
                if (Math.abs(p.x - c.x | 0) <= 1 && Math.abs(p.y - c.y | 0) <= 1) {
                  return Caml_obj.caml_notequal(p, c);
                } else {
                  return false;
                }
              }));
}

function nextObjStatus(obj, adjacents) {
  var notOccupied = function (param, obj) {
    return obj !== /* Occupied */0;
  };
  var occupiedSeatsCount = function (a) {
    return Belt_Map.size(Belt_Map.keep(a, (function (param, obj) {
                      return obj === /* Occupied */0;
                    })));
  };
  switch (obj) {
    case /* Occupied */0 :
        if (4 <= occupiedSeatsCount(adjacents)) {
          return /* Empty */1;
        } else {
          return obj;
        }
    case /* Empty */1 :
        if (Belt_Map.every(adjacents, notOccupied)) {
          return /* Occupied */0;
        } else {
          return obj;
        }
    case /* Floor */2 :
        return obj;
    
  }
}

function nextMapStatus(seatingMap) {
  return Belt_Map.mapWithKey(seatingMap, (function (current, obj) {
                return nextObjStatus(obj, adjacentSeats(current, seatingMap));
              }));
}

function findNoChangeState(_seatingMap, nextMapStatus) {
  while(true) {
    var seatingMap = _seatingMap;
    var next = Curry._1(nextMapStatus, seatingMap);
    if (Caml_obj.caml_equal(next, seatingMap)) {
      return seatingMap;
    }
    _seatingMap = next;
    continue ;
  };
}

function countOccupiedSeats(seatingMap) {
  var occupied = function (param, v) {
    return v === /* Occupied */0;
  };
  return Belt_Map.size(Belt_Map.keep(seatingMap, occupied));
}

function printMap(seatingMap) {
  var prnStr = {
    contents: ""
  };
  var append = function ($$char) {
    prnStr.contents = prnStr.contents + $$char;
    
  };
  Belt_Range.forEach(0, height - 1 | 0, (function (y) {
          Belt_Range.forEach(0, width - 1 | 0, (function (x) {
                  return append(objToChar(Belt_Option.getWithDefault(Belt_Map.get(seatingMap, {
                                          x: x,
                                          y: y
                                        }), /* Floor */2)));
                }));
          return append("\n");
        }));
  console.log(prnStr.contents);
  
}

function validate(seatingMap) {
  var occupied = function (param, obj) {
    return Caml_obj.caml_equal(obj, /* Occupied */0);
  };
  var occupiedSeatsCount = function (a) {
    return Belt_Map.size(Belt_Map.keep(a, (function (param, obj) {
                      return Caml_obj.caml_equal(obj, /* Occupied */0);
                    })));
  };
  return Belt_Map.every(seatingMap, (function (k, v) {
                var adj = adjacentSeats(k, seatingMap);
                if (v === undefined) {
                  return true;
                }
                switch (v) {
                  case /* Occupied */0 :
                      return occupiedSeatsCount(adj) < 4;
                  case /* Empty */1 :
                      return Belt_Map.some(adj, occupied);
                  case /* Floor */2 :
                      return true;
                  
                }
              }));
}

Belt_Range.forEach(0, 3, (function (prim) {
        console.log(prim);
        
      }));

function add(a, b) {
  return {
          x: a.x + b.x | 0,
          y: a.y + b.y | 0
        };
}

var direcs = [
  {
    x: -1,
    y: -1
  },
  {
    x: -1,
    y: 0
  },
  {
    x: -1,
    y: 1
  },
  {
    x: 0,
    y: -1
  },
  {
    x: 0,
    y: 1
  },
  {
    x: 1,
    y: -1
  },
  {
    x: 1,
    y: 0
  },
  {
    x: 1,
    y: 1
  }
];

function isValidLoc(p) {
  if (0 <= p.x && p.x < width && 0 <= p.y) {
    return p.y < height;
  } else {
    return false;
  }
}

function nextStep(current, dir) {
  var next = add(current, dir);
  if (isValidLoc(next)) {
    return [
            next,
            dir
          ];
  }
  
}

function occupiedCountFromAdjacent(smap, curr) {
  return Belt_Array.keep(Belt_Array.keepMap(Belt_Array.keepMap(direcs, (function (d) {
                        return nextStep(curr, d);
                      })), (function (param) {
                    return Belt_Map.get(smap, param[0]);
                  })), (function (o) {
                return o === /* Occupied */0;
              })).length;
}

function occupiedCountFromSight(smap, curr) {
  return Belt_Array.reduce(Belt_Array.map(Belt_Array.keepMap(direcs, (function (d) {
                        return nextStep(curr, d);
                      })), (function (param) {
                    var _current = param[0];
                    var dir = param[1];
                    while(true) {
                      var current = _current;
                      var currObj = Belt_Map.get(smap, current);
                      var nextL = nextStep(current, dir);
                      if (currObj === undefined) {
                        return 0;
                      }
                      switch (currObj) {
                        case /* Occupied */0 :
                            return 1;
                        case /* Empty */1 :
                            return 0;
                        case /* Floor */2 :
                            if (nextL === undefined) {
                              return 0;
                            }
                            _current = nextL[0];
                            continue ;
                        
                      }
                    };
                  })), 0, (function (a, b) {
                return a + b | 0;
              }));
}

function nextObjStatus2(smap, curr, obj) {
  var countSight = occupiedCountFromSight(smap, curr);
  var countAdjacent = occupiedCountFromAdjacent(smap, curr);
  if (curr.x === 2 && curr.y === 0) {
    console.log("(2,0)", objToChar(obj), countSight, countAdjacent);
  }
  switch (obj) {
    case /* Occupied */0 :
        if (5 <= countSight) {
          return /* Empty */1;
        } else {
          return obj;
        }
    case /* Empty */1 :
        if (countSight === 0) {
          return /* Occupied */0;
        } else {
          return obj;
        }
    case /* Floor */2 :
        return obj;
    
  }
}

function nextMapStatus2(sMap) {
  return Belt_Map.mapWithKey(sMap, (function (current, obj) {
                return nextObjStatus2(sMap, current, obj);
              }));
}

function findNoChangeState2(_sMap, nextMapStatus) {
  while(true) {
    var sMap = _sMap;
    var next = Curry._1(nextMapStatus, sMap);
    printMap(next);
    if (Caml_obj.caml_equal(next, sMap)) {
      return sMap;
    }
    _sMap = next;
    continue ;
  };
}

function countOccupiedSeats2(sMap) {
  var isOccupied = function (param, v) {
    return v === /* Occupied */0;
  };
  return Belt_Map.size(Belt_Map.keep(sMap, isOccupied));
}

function printMap2(seatingMap) {
  var prnStr = {
    contents: ""
  };
  var append = function ($$char) {
    prnStr.contents = prnStr.contents + $$char;
    
  };
  Belt_Range.forEach(0, height - 1 | 0, (function (y) {
          Belt_Range.forEach(0, width - 1 | 0, (function (x) {
                  return append(objToChar(Belt_Option.getWithDefault(Belt_Map.get(seatingMap, {
                                          x: x,
                                          y: y
                                        }), /* Floor */2)));
                }));
          return append("\n");
        }));
  console.log(prnStr.contents);
  return seatingMap;
}

console.log("Height : ");

console.log(height);

console.log(width);

var initMap = initialize(undefined);

console.log(countOccupiedSeats2(findNoChangeState2(initMap, nextMapStatus2)));

exports.mapInputs = mapInputs;
exports.width = width;
exports.height = height;
exports.PointCmp = PointCmp;
exports.charToObj = charToObj;
exports.objToChar = objToChar;
exports.initialize = initialize;
exports.adjacentSeats = adjacentSeats;
exports.nextObjStatus = nextObjStatus;
exports.nextMapStatus = nextMapStatus;
exports.findNoChangeState = findNoChangeState;
exports.countOccupiedSeats = countOccupiedSeats;
exports.printMap = printMap;
exports.validate = validate;
exports.add = add;
exports.direcs = direcs;
exports.isValidLoc = isValidLoc;
exports.nextStep = nextStep;
exports.occupiedCountFromAdjacent = occupiedCountFromAdjacent;
exports.occupiedCountFromSight = occupiedCountFromSight;
exports.nextObjStatus2 = nextObjStatus2;
exports.nextMapStatus2 = nextMapStatus2;
exports.findNoChangeState2 = findNoChangeState2;
exports.countOccupiedSeats2 = countOccupiedSeats2;
exports.printMap2 = printMap2;
exports.initMap = initMap;
/* mapInputs Not a pure module */
