// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Belt_SetInt = require("bs-platform/lib/js/belt_SetInt.js");

function SpreadSheet(Calculator) {
  var puzzleInput = function (fileName) {
    return Fs.readFileSync(fileName, "utf8").split("\n");
  };
  var row = function (inputRow) {
    return Belt_Array.keepMap(Belt_Array.keepMap(inputRow.split(/\s+/), (function (x) {
                      return x;
                    })), Calculator.strConverter);
  };
  var rows = function (puzzleInput) {
    return Belt_Array.map(puzzleInput, row);
  };
  var checksum = Belt_Array.reduce(Belt_Array.map(Belt_Array.map(Fs.readFileSync("./res/day2017-2.txt", "utf8").split("\n"), row), Calculator.result), Calculator.initializer, Calculator.appender);
  return {
          puzzleInput: puzzleInput,
          row: row,
          rows: rows,
          checksum: checksum
        };
}

function result(row) {
  var s = Belt_SetInt.fromArray(row);
  var match = Belt_SetInt.maximum(s);
  var match$1 = Belt_SetInt.minimum(s);
  if (match !== undefined && match$1 !== undefined) {
    return match - match$1 | 0;
  } else {
    return 0;
  }
}

function appender(a, b) {
  return a + b | 0;
}

var P1Calculator = {
  strConverter: Belt_Int.fromString,
  result: result,
  initializer: 0,
  appender: appender
};

function puzzleInput(fileName) {
  return Fs.readFileSync(fileName, "utf8").split("\n");
}

function row(inputRow) {
  return Belt_Array.keepMap(Belt_Array.keepMap(inputRow.split(/\s+/), (function (x) {
                    return x;
                  })), Belt_Int.fromString);
}

function rows(puzzleInput) {
  return Belt_Array.map(puzzleInput, row);
}

var checksum = Belt_Array.reduce(Belt_Array.map(Belt_Array.map(Fs.readFileSync("./res/day2017-2.txt", "utf8").split("\n"), row), result), 0, appender);

var SpreadSheetP1 = {
  puzzleInput: puzzleInput,
  row: row,
  rows: rows,
  checksum: checksum
};

console.log(checksum);

function result$1(row) {
  return Belt_Option.getWithDefault(Belt_Array.get(Belt_Array.keepMap(row, (function (a) {
                        return Belt_Option.map(Belt_Array.getBy(row, (function (param) {
                                          if (Caml_int32.mod_(a, param) === 0) {
                                            return a > param;
                                          } else {
                                            return false;
                                          }
                                        })), (function (b) {
                                      return Caml_int32.div(a, b);
                                    }));
                      })), 0), 0);
}

function appender$1(a, b) {
  return a + b | 0;
}

var P2Calculator = {
  strConverter: Belt_Int.fromString,
  result: result$1,
  initializer: 0,
  appender: appender$1
};

function puzzleInput$1(fileName) {
  return Fs.readFileSync(fileName, "utf8").split("\n");
}

function row$1(inputRow) {
  return Belt_Array.keepMap(Belt_Array.keepMap(inputRow.split(/\s+/), (function (x) {
                    return x;
                  })), Belt_Int.fromString);
}

function rows$1(puzzleInput) {
  return Belt_Array.map(puzzleInput, row$1);
}

var checksum$1 = Belt_Array.reduce(Belt_Array.map(Belt_Array.map(Fs.readFileSync("./res/day2017-2.txt", "utf8").split("\n"), row$1), result$1), 0, appender$1);

var SpreadSheetP2 = {
  puzzleInput: puzzleInput$1,
  row: row$1,
  rows: rows$1,
  checksum: checksum$1
};

console.log(checksum$1);

exports.SpreadSheet = SpreadSheet;
exports.P1Calculator = P1Calculator;
exports.SpreadSheetP1 = SpreadSheetP1;
exports.P2Calculator = P2Calculator;
exports.SpreadSheetP2 = SpreadSheetP2;
/* checksum Not a pure module */
