// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function convertToObj(x) {
  if (x.length !== 4) {
    throw {
          RE_EXN_ID: "Not_found",
          Error: new Error()
        };
  }
  var a0 = x[0];
  var a1 = x[1];
  var a2 = x[2];
  var a3 = x[3];
  return {
          min: Belt_Option.getExn(Belt_Int.fromString(a0)),
          max: Belt_Option.getExn(Belt_Int.fromString(a1)),
          ch: a2,
          word: a3
        };
}

var parsedList = Belt_Array.keepMap(Fs.readFileSync("res/day2.txt", "utf8").trim().split("\n"), (function (s) {
        return Belt_Option.map(Caml_option.null_to_opt(s.trim().match(/(\d+)-(\d+) (\w): (\w+)/)), (function (a) {
                      return Belt_Array.sliceToEnd(a, 1);
                    }));
      }));

function countChar(ch, word) {
  var arr = Array.from(word, (function (x) {
          return x;
        }));
  return Belt_Array.keep(arr, (function (x) {
                return x === ch;
              })).length;
}

function isInRange(min, max, number) {
  if (Caml_obj.caml_lessequal(min, number)) {
    return Caml_obj.caml_lessequal(number, max);
  } else {
    return false;
  }
}

function isValid(param) {
  var count = countChar(param.ch, param.word);
  return isInRange(param.min, param.max, count);
}

var solution = Belt_Array.keep(Belt_Array.map(parsedList, convertToObj), isValid).length;

function convertToP2(x) {
  if (x.length !== 4) {
    throw {
          RE_EXN_ID: "Not_found",
          Error: new Error()
        };
  }
  var a0 = x[0];
  var a1 = x[1];
  var a2 = x[2];
  var a3 = x[3];
  return {
          first: Belt_Option.getExn(Belt_Int.fromString(a0)),
          second: Belt_Option.getExn(Belt_Int.fromString(a1)),
          ch: a2,
          word: a3
        };
}

function isValidP2(param) {
  var word = param.word;
  var ch = param.ch;
  var second = param.second;
  var first = param.first;
  if (word.charAt(first - 1 | 0) === ch && word.charAt(second - 1 | 0) !== ch) {
    return true;
  } else if (word.charAt(first - 1 | 0) !== ch) {
    return word.charAt(second - 1 | 0) === ch;
  } else {
    return false;
  }
}

var solutionP2 = Belt_Array.keep(Belt_Array.map(parsedList, convertToP2), isValidP2).length;

console.log("Test 1 : ");

console.log(isValid({
          min: 2,
          max: 4,
          ch: "s",
          word: "skss"
        }));

console.log("Test 2 : ");

console.log(isValid({
          min: 10,
          max: 17,
          ch: "j",
          word: "jjjjjjjjjfjjjjjjk"
        }));

console.log("Test 3 : ");

console.log(isValid({
          min: 2,
          max: 3,
          ch: "x",
          word: "fxpr"
        }));

console.log("Test 4 : ");

console.log(isValid({
          min: 1,
          max: 3,
          ch: "a",
          word: "abcde"
        }));

console.log("Test 5 : ");

console.log(isValid({
          min: 1,
          max: 3,
          ch: "b",
          word: "cdefg"
        }));

console.log("Test 6 : ");

console.log(isValid({
          min: 2,
          max: 9,
          ch: "c",
          word: "ccccccccc"
        }));

console.log("Test 7 : ");

console.log(isValid({
          min: 2,
          max: 3,
          ch: "e",
          word: "cdeeeefg"
        }));

console.log("Day 2 P1 solution : ");

console.log(solution);

console.log("Day 2 P2 solution : ");

console.log(solutionP2);

exports.convertToObj = convertToObj;
exports.parsedList = parsedList;
exports.countChar = countChar;
exports.isInRange = isInRange;
exports.isValid = isValid;
exports.solution = solution;
exports.convertToP2 = convertToP2;
exports.isValidP2 = isValidP2;
exports.solutionP2 = solutionP2;
/* parsedList Not a pure module */
