// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

var initialData = {
  number: 1,
  len: 0,
  steps: {
    down: 0,
    left: 0
  },
  direct: /* Left */2
};

function nextPos(param, direct) {
  var left = param.left;
  var down = param.down;
  switch (direct) {
    case /* Up */0 :
        return {
                down: down - 1 | 0,
                left: left
              };
    case /* Down */1 :
        return {
                down: down + 1 | 0,
                left: left
              };
    case /* Left */2 :
        return {
                down: down,
                left: left + 1 | 0
              };
    case /* Right */3 :
        return {
                down: down,
                left: left - 1 | 0
              };
    
  }
}

var Mover = {
  nextPos: nextPos
};

function nextStep(data) {
  return {
          number: data.number + 1 | 0,
          len: data.len,
          steps: nextPos(data.steps, data.direct),
          direct: data.direct
        };
}

function next(data) {
  var len = data.len;
  var next$1 = nextStep(data);
  var match = next$1.steps;
  var left = match.left;
  var down = match.down;
  if ((-down | 0) === len && left === (len + 1 | 0)) {
    return {
            number: next$1.number,
            len: len + 1 | 0,
            steps: next$1.steps,
            direct: /* Down */1
          };
  } else if (down === len && left === len) {
    return {
            number: next$1.number,
            len: next$1.len,
            steps: next$1.steps,
            direct: /* Right */3
          };
  } else if (down === len && left === (-len | 0)) {
    return {
            number: next$1.number,
            len: next$1.len,
            steps: next$1.steps,
            direct: /* Up */0
          };
  } else if (down === (-len | 0) && left === (-len | 0)) {
    return {
            number: next$1.number,
            len: next$1.len,
            steps: next$1.steps,
            direct: /* Left */2
          };
  } else {
    return next$1;
  }
}

function logRet(x) {
  console.log(x);
  return x;
}

function findStep(number) {
  var _data = initialData;
  while(true) {
    var data = _data;
    if (data.number === number) {
      return data;
    }
    _data = next(data);
    continue ;
  };
}

findStep(1024);

var s = findStep(347991);

var s$1 = s.steps;

Math.abs(s$1.down) + Math.abs(s$1.left) | 0;

function sumNeighBors(steps, previous) {
  var isNeighBor = function (cand) {
    var downDiff = Math.abs(steps.down - cand.steps.down | 0);
    var leftDiff = Math.abs(steps.left - cand.steps.left | 0);
    if (downDiff <= 1) {
      return leftDiff <= 1;
    } else {
      return false;
    }
  };
  return Belt_List.reduce(Belt_List.map(Belt_List.keep(previous, isNeighBor), (function (d) {
                    return d.number;
                  })), 0, (function (x, y) {
                return x + y | 0;
              }));
}

function nextStepP2(previous) {
  var data = Belt_List.headExn(previous);
  var nextSteps = nextPos(data.steps, data.direct);
  return {
          number: sumNeighBors(nextSteps, previous),
          len: data.len,
          steps: nextSteps,
          direct: data.direct
        };
}

function nextP2(previous) {
  var match = Belt_List.headExn(previous);
  var len = match.len;
  var nextStep = nextStepP2(previous);
  var match$1 = nextStep.steps;
  var left = match$1.left;
  var down = match$1.down;
  var nextData = (-down | 0) === len && left === (len + 1 | 0) ? ({
        number: nextStep.number,
        len: len + 1 | 0,
        steps: nextStep.steps,
        direct: /* Down */1
      }) : (
      down === len && left === len ? ({
            number: nextStep.number,
            len: nextStep.len,
            steps: nextStep.steps,
            direct: /* Right */3
          }) : (
          down === len && left === (-len | 0) ? ({
                number: nextStep.number,
                len: nextStep.len,
                steps: nextStep.steps,
                direct: /* Up */0
              }) : (
              down === (-len | 0) && left === (-len | 0) ? ({
                    number: nextStep.number,
                    len: nextStep.len,
                    steps: nextStep.steps,
                    direct: /* Left */2
                  }) : nextStep
            )
        )
    );
  return Belt_List.add(previous, nextData);
}

function findStepP2(input) {
  var _stepList = {
    hd: initialData,
    tl: /* [] */0
  };
  while(true) {
    var stepList = _stepList;
    var match = Belt_List.head(stepList);
    if (match !== undefined) {
      var number = match.number;
      if (number > input) {
        return number;
      }
      _stepList = nextP2(stepList);
      continue ;
    }
    _stepList = nextP2(stepList);
    continue ;
  };
}

console.log(findStepP2(347991));

var sample1 = 1;

exports.sample1 = sample1;
exports.initialData = initialData;
exports.Mover = Mover;
exports.nextStep = nextStep;
exports.next = next;
exports.logRet = logRet;
exports.findStep = findStep;
exports.sumNeighBors = sumNeighBors;
exports.nextStepP2 = nextStepP2;
exports.nextP2 = nextP2;
exports.findStepP2 = findStepP2;
/*  Not a pure module */
