// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function getType(ch) {
  switch (ch) {
    case "#" :
        return /* Tree */1;
    case "." :
        return /* OpenSquare */0;
    default:
      return /* None */2;
  }
}

function getArea(m) {
  return {
          map: m,
          width: Belt_Array.getExn(m, 0).length,
          height: m.length
        };
}

function makeMap(strings) {
  return Belt_Array.mapWithIndex(strings, (function (y, row) {
                return Belt_Array.mapWithIndex(Array.from(row, (function (x) {
                                  return x;
                                })), (function (x, ch) {
                              return {
                                      obj: getType(ch),
                                      x: x,
                                      y: y
                                    };
                            }));
              }));
}

var parsedList = Fs.readFileSync("res/day3.txt", "utf8");

var strings = makeMap(parsedList.split("\n"));

var area = getArea(strings);

function explore(area, param, mapRow) {
  var slope = param.slope;
  var row = param.row;
  var col = param.col;
  var count = param.count;
  var cell = Belt_Array.getExn(mapRow, col);
  return {
          count: row === cell.y && cell.obj === /* Tree */1 ? count + 1 | 0 : count,
          col: row === cell.y ? Caml_int32.mod_(col + slope.x | 0, area.width) : col,
          row: row === cell.y ? row + slope.y | 0 : row,
          slope: slope
        };
}

var slopeP1 = {
  x: 3,
  y: 1
};

var solutionP1 = Belt_Array.reduce(area.map, {
      count: 0,
      col: 0,
      row: 0,
      slope: slopeP1
    }, (function (param, param$1) {
        return explore(area, param, param$1);
      }));

console.log(solutionP1.count);

var p2Slopes = [
  {
    x: 1,
    y: 1
  },
  slopeP1,
  {
    x: 5,
    y: 1
  },
  {
    x: 7,
    y: 1
  },
  {
    x: 1,
    y: 2
  }
];

var p2Init = Belt_Array.map(p2Slopes, (function (s) {
        return {
                count: 0,
                col: 0,
                row: 0,
                slope: s
              };
      }));

var p2Results = Belt_Array.map(Belt_Array.map(p2Init, (function (i) {
            return Belt_Array.reduce(area.map, i, (function (param, param$1) {
                          return explore(area, param, param$1);
                        }));
          })), (function (i) {
        return i.count;
      }));

console.log(p2Results);

var p2Counts = Belt_Array.reduce(p2Results, 1, (function (x, y) {
        return x * y;
      }));

console.log(p2Counts);

exports.getType = getType;
exports.getArea = getArea;
exports.makeMap = makeMap;
exports.parsedList = parsedList;
exports.strings = strings;
exports.area = area;
exports.explore = explore;
exports.slopeP1 = slopeP1;
exports.solutionP1 = solutionP1;
exports.p2Slopes = p2Slopes;
exports.p2Init = p2Init;
exports.p2Results = p2Results;
exports.p2Counts = p2Counts;
/* parsedList Not a pure module */
