// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

var passportTemplate = {
  byr: 1920,
  iyr: 2010,
  eyr: 2020,
  hgt: {
    TAG: /* CM */0,
    _0: 150
  },
  hcl: "#ffffff",
  ecl: /* AMB */0,
  pid: "012345678",
  cid: undefined
};

function parseByr(byrInput) {
  var x = Belt_Int.fromString(byrInput);
  if (x !== undefined && 1920 <= x && x <= 2002) {
    return x;
  }
  
}

function parseIyr(iyrInput) {
  var x = Belt_Int.fromString(iyrInput);
  if (x !== undefined && 2010 <= x && x <= 2020) {
    return x;
  }
  
}

function parseEyr(eyrInput) {
  var x = Belt_Int.fromString(eyrInput);
  if (x !== undefined && 2020 <= x && x <= 2030) {
    return x;
  }
  
}

function parseHgt(hgtInput) {
  var x = hgtInput.match(/(\d+)(\w+)/);
  var x$1 = x === null ? undefined : Caml_option.some(x);
  var a;
  if (x !== null && x$1.length === 3) {
    var num = x$1[1];
    var _type = x$1[2];
    var match = Belt_Int.fromString(num);
    if (match !== undefined) {
      switch (_type) {
        case "cm" :
            a = {
              TAG: /* CM */0,
              _0: match
            };
            break;
        case "in" :
            a = {
              TAG: /* INCH */1,
              _0: match
            };
            break;
        default:
          a = undefined;
      }
    } else {
      a = undefined;
    }
  } else {
    a = undefined;
  }
  if (a === undefined) {
    return ;
  }
  if (a.TAG === /* CM */0) {
    var x$2 = a._0;
    if (150 <= x$2 && x$2 <= 193) {
      return a;
    } else {
      return ;
    }
  }
  var x$3 = a._0;
  if (59 <= x$3 && x$3 <= 76) {
    return a;
  }
  
}

function parseHcl(hclInput) {
  return Belt_Option.flatMap(Caml_option.null_to_opt(hclInput.match(/#[0-9a-f]{6}/)), (function (y) {
                if (y.length === 1) {
                  return hclInput;
                }
                
              }));
}

function parseEcl(eclInput) {
  switch (eclInput) {
    case "amb" :
        return /* AMB */0;
    case "blu" :
        return /* BLU */1;
    case "brn" :
        return /* BRN */2;
    case "grn" :
        return /* GRN */4;
    case "gry" :
        return /* GRY */3;
    case "hzl" :
        return /* HZL */5;
    case "oth" :
        return /* OTH */6;
    default:
      return ;
  }
}

function parsePid(pidInput) {
  var match = pidInput.match(/\d{9}/);
  if (match !== null) {
    return pidInput;
  }
  
}

function parseCid(cidInput) {
  return Caml_option.some(cidInput);
}

function parsePassport(s) {
  return Belt_Array.reduce(Belt_Array.map(s.split(/\s/), (function (s) {
                    return Belt_Option.getExn(s).split(":");
                  })), passportTemplate, (function (passport, arr) {
                if (arr.length !== 2) {
                  return passport;
                }
                var match = arr[0];
                switch (match) {
                  case "byr" :
                      var val = arr[1];
                      return {
                              byr: Belt_Option.getExn(parseByr(val)),
                              iyr: passport.iyr,
                              eyr: passport.eyr,
                              hgt: passport.hgt,
                              hcl: passport.hcl,
                              ecl: passport.ecl,
                              pid: passport.pid,
                              cid: passport.cid
                            };
                  case "cid" :
                      var val$1 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: passport.iyr,
                              eyr: passport.eyr,
                              hgt: passport.hgt,
                              hcl: passport.hcl,
                              ecl: passport.ecl,
                              pid: passport.pid,
                              cid: Caml_option.some(val$1)
                            };
                  case "ecl" :
                      var val$2 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: passport.iyr,
                              eyr: passport.eyr,
                              hgt: passport.hgt,
                              hcl: passport.hcl,
                              ecl: Belt_Option.getExn(parseEcl(val$2)),
                              pid: passport.pid,
                              cid: passport.cid
                            };
                  case "eyr" :
                      var val$3 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: passport.iyr,
                              eyr: Belt_Option.getExn(parseEyr(val$3)),
                              hgt: passport.hgt,
                              hcl: passport.hcl,
                              ecl: passport.ecl,
                              pid: passport.pid,
                              cid: passport.cid
                            };
                  case "hcl" :
                      var val$4 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: passport.iyr,
                              eyr: passport.eyr,
                              hgt: passport.hgt,
                              hcl: Belt_Option.getExn(parseHcl(val$4)),
                              ecl: passport.ecl,
                              pid: passport.pid,
                              cid: passport.cid
                            };
                  case "hgt" :
                      var val$5 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: passport.iyr,
                              eyr: passport.eyr,
                              hgt: Belt_Option.getExn(parseHgt(val$5)),
                              hcl: passport.hcl,
                              ecl: passport.ecl,
                              pid: passport.pid,
                              cid: passport.cid
                            };
                  case "iyr" :
                      var val$6 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: Belt_Option.getExn(parseIyr(val$6)),
                              eyr: passport.eyr,
                              hgt: passport.hgt,
                              hcl: passport.hcl,
                              ecl: passport.ecl,
                              pid: passport.pid,
                              cid: passport.cid
                            };
                  case "pid" :
                      var val$7 = arr[1];
                      return {
                              byr: passport.byr,
                              iyr: passport.iyr,
                              eyr: passport.eyr,
                              hgt: passport.hgt,
                              hcl: passport.hcl,
                              ecl: passport.ecl,
                              pid: Belt_Option.getExn(parsePid(val$7)),
                              cid: passport.cid
                            };
                  default:
                    return passport;
                }
              }));
}

var inputStr = Fs.readFileSync("res/day4.txt", "utf8");

var passportStrs = inputStr.split("\n\n");

console.log(passportStrs.length);

var arrs = Belt_Array.keepMap(passportStrs, (function (st) {
        var p;
        try {
          p = parsePassport(st);
        }
        catch (raw_exn){
          var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
          if (exn.RE_EXN_ID === "Not_found") {
            return ;
          }
          throw exn;
        }
        return p;
      }));

console.log(arrs.length);

exports.passportTemplate = passportTemplate;
exports.parseByr = parseByr;
exports.parseIyr = parseIyr;
exports.parseEyr = parseEyr;
exports.parseHgt = parseHgt;
exports.parseHcl = parseHcl;
exports.parseEcl = parseEcl;
exports.parsePid = parsePid;
exports.parseCid = parseCid;
exports.parsePassport = parsePassport;
exports.inputStr = inputStr;
exports.passportStrs = passportStrs;
exports.arrs = arrs;
/* inputStr Not a pure module */
