// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_SetInt = require("bs-platform/lib/js/belt_SetInt.js");

var inputStr = Fs.readFileSync("res/day5.txt", "utf8");

var seatStrs = inputStr.split("\n");

function makeArray(str) {
  return Array.from(str, (function (x) {
                return x;
              }));
}

function calcRowCol(strArr) {
  var param = Belt_Array.reduce(strArr, [
        0,
        127,
        0,
        7
      ], (function (param, $$char) {
          var maxCol = param[3];
          var minCol = param[2];
          var maxRow = param[1];
          var minRow = param[0];
          switch ($$char) {
            case "B" :
                return [
                        minRow + (((maxRow - minRow | 0) + 1 | 0) / 2 | 0) | 0,
                        maxRow,
                        minCol,
                        maxCol
                      ];
            case "F" :
                return [
                        minRow,
                        maxRow - (((maxRow - minRow | 0) + 1 | 0) / 2 | 0) | 0,
                        minCol,
                        maxCol
                      ];
            case "L" :
                return [
                        minRow,
                        maxRow,
                        minCol,
                        maxCol - (((maxCol - minCol | 0) + 1 | 0) / 2 | 0) | 0
                      ];
            case "R" :
                return [
                        minRow,
                        maxRow,
                        minCol + (((maxCol - minCol | 0) + 1 | 0) / 2 | 0) | 0,
                        maxCol
                      ];
            default:
              return Js_exn.raiseError("Unexpected input.");
          }
        }));
  return [
          param[0],
          param[2]
        ];
}

function getSeatID(param) {
  return (param[0] << 3) + param[1] | 0;
}

function strToSeatID(str) {
  return getSeatID(calcRowCol(Array.from(str, (function (x) {
                        return x;
                      }))));
}

var seatIDSet = Belt_SetInt.fromArray(Belt_Array.map(seatStrs, strToSeatID));

console.log(Belt_SetInt.maximum(seatIDSet));

function isNearByMySeatID(n) {
  if (Belt_SetInt.some(seatIDSet, (function (x) {
            return (x - 2 | 0) === n;
          }))) {
    return Belt_SetInt.every(seatIDSet, (function (x) {
                  return (x - 1 | 0) !== n;
                }));
  } else {
    return false;
  }
}

var solutionP2 = Belt_Array.getExn(Belt_SetInt.toArray(Belt_SetInt.keep(seatIDSet, isNearByMySeatID)), 0) + 1 | 0;

console.log(solutionP2);

var strSample = "BBFFBBFRLL";

var solutionP1;

exports.inputStr = inputStr;
exports.seatStrs = seatStrs;
exports.strSample = strSample;
exports.makeArray = makeArray;
exports.calcRowCol = calcRowCol;
exports.getSeatID = getSeatID;
exports.strToSeatID = strToSeatID;
exports.seatIDSet = seatIDSet;
exports.solutionP1 = solutionP1;
exports.isNearByMySeatID = isNearByMySeatID;
exports.solutionP2 = solutionP2;
/* inputStr Not a pure module */
