// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");

function getGroupInputs(fIn) {
  return fIn.split("\n\n");
}

function getPersonInputs(grpIn) {
  return grpIn.split("\n");
}

function getAnswers(psIn) {
  return Belt_SetString.fromArray(Array.from(psIn, (function (x) {
                    return x;
                  })));
}

function getGrpAnswers(fn, grpIn) {
  var answers = Belt_Array.map(grpIn.split("\n"), getAnswers);
  var first = Belt_Array.getExn(answers, 0);
  return Belt_Array.reduce(answers, first, fn);
}

var grpInputs = Fs.readFileSync("res/day6.txt", "utf8").split("\n\n");

function totalAnswer(answers) {
  return Belt_Array.reduce(Belt_Array.map(answers, Belt_SetString.size), 0, (function (x, y) {
                return x + y | 0;
              }));
}

function solveBy(fn) {
  console.log(totalAnswer(Belt_Array.map(grpInputs, (function (param) {
                  return getGrpAnswers(fn, param);
                }))));
  
}

var solutionP1 = solveBy(Belt_SetString.union);

var solutionP2 = solveBy(Belt_SetString.intersect);

exports.getGroupInputs = getGroupInputs;
exports.getPersonInputs = getPersonInputs;
exports.getAnswers = getAnswers;
exports.getGrpAnswers = getGrpAnswers;
exports.grpInputs = grpInputs;
exports.totalAnswer = totalAnswer;
exports.solveBy = solveBy;
exports.solutionP1 = solutionP1;
exports.solutionP2 = solutionP2;
/* grpInputs Not a pure module */
