// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");

function readFile(fileName) {
  return Fs.readFileSync(fileName, "utf8");
}

function splitByLF(input) {
  return input.split("\n");
}

function getObjectColor(sentence) {
  return Belt_Option.flatMap(Caml_option.null_to_opt(sentence.match(/([\w\s]+) bags contain|contains/)), (function (s) {
                return Belt_Array.get(s, 1);
              }));
}

function getContainsPart(sentence) {
  return Belt_Option.flatMap(Caml_option.null_to_opt(sentence.match(/[\w\s]+ bags (contain|contains) (.+)\./)), (function (s) {
                return Belt_Array.get(s, 2);
              }));
}

function splitContainerPart(s) {
  if (s !== undefined) {
    return s.split(/, /);
  } else {
    return [];
  }
}

function getColorAndNumber(s) {
  if (s === "no other bags") {
    return ;
  } else {
    return Belt_Option.flatMap(Belt_Option.map(Caml_option.null_to_opt(s.match(/(\d+) ([\s\w]+) bag|bags/)), (function (a) {
                      return [
                              Belt_Option.flatMap(Belt_Array.get(a, 1), Belt_Int.fromString),
                              Belt_Array.get(a, 2)
                            ];
                    })), (function (x) {
                  var n = x[0];
                  if (n === undefined) {
                    return ;
                  }
                  var c = x[1];
                  if (c !== undefined) {
                    return [
                            c,
                            n
                          ];
                  }
                  
                }));
  }
}

function getContentInfo(s) {
  return Belt_Array.keepMap(splitContainerPart(getContainsPart(s)), (function (x) {
                return Belt_Option.flatMap(x, getColorAndNumber);
              }));
}

function generateBags(sentences) {
  return Belt_Array.map(Belt_Array.map(sentences, (function (s) {
                    return [
                            getObjectColor(s),
                            getContentInfo(s)
                          ];
                  })), (function (param) {
                return {
                        color: Belt_Option.getWithDefault(param[0], ""),
                        contains: param[1]
                      };
              }));
}

function bagKinds(bags, tailTarget) {
  var findingContainer = function (set, target) {
    return Belt_Array.reduce(Belt_Array.keep(Belt_Array.map(bags, (function (b) {
                          return b.color;
                        })), (function (c) {
                      return Belt_Array.some(Belt_Option.mapWithDefault(Belt_Array.getBy(bags, (function (a) {
                                            return Caml_obj.caml_equal(a.color, c);
                                          })), [], (function (a) {
                                        return a.contains;
                                      })), (function (param) {
                                    return Caml_obj.caml_equal(param[0], target);
                                  }));
                    })), Belt_SetString.add(set, target), findingContainer);
  };
  return findingContainer(undefined, tailTarget);
}

var bags = generateBags(Fs.readFileSync("./res/day7.txt", "utf8").split("\n"));

console.log(Belt_SetString.size(bagKinds(bags, "shiny gold")) - 1 | 0);

function bagVolume(bags, mainColor) {
  var countSubBag = function (color) {
    return Belt_Array.reduce(Belt_Option.mapWithDefault(Belt_Array.getBy(bags, (function (b) {
                          return Caml_obj.caml_equal(b.color, color);
                        })), [], (function (b) {
                      return b.contains;
                    })), 1, (function (cnt, param) {
                  return cnt + Math.imul(param[1], countSubBag(param[0])) | 0;
                }));
  };
  return countSubBag(mainColor) - 1 | 0;
}

console.log(bagVolume(bags, "shiny gold"));

var b;

exports.readFile = readFile;
exports.splitByLF = splitByLF;
exports.getObjectColor = getObjectColor;
exports.getContainsPart = getContainsPart;
exports.splitContainerPart = splitContainerPart;
exports.getColorAndNumber = getColorAndNumber;
exports.getContentInfo = getContentInfo;
exports.generateBags = generateBags;
exports.bagKinds = bagKinds;
exports.bags = bags;
exports.bagVolume = bagVolume;
exports.b = b;
/* bags Not a pure module */
