// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function getInstruction(s) {
  if (s === undefined) {
    return ;
  }
  if (s.length !== 3) {
    return ;
  }
  var match = s[1];
  switch (match) {
    case "acc" :
        var num = s[2];
        return {
                TAG: /* Acc */1,
                _0: Belt_Option.getWithDefault(Belt_Int.fromString(num), 0)
              };
    case "jmp" :
        var num$1 = s[2];
        return {
                TAG: /* Jmp */2,
                _0: Belt_Option.getWithDefault(Belt_Int.fromString(num$1), 0)
              };
    case "nop" :
        var num$2 = s[2];
        return {
                TAG: /* Nop */0,
                _0: Belt_Option.getWithDefault(Belt_Int.fromString(num$2), 0)
              };
    default:
      return ;
  }
}

function parseLine(line) {
  return getInstruction(Caml_option.null_to_opt(line.match(/(nop|acc|jmp) (\+\d+|\-\d+)/)));
}

function nextInstruction(instruction, line, currVal) {
  switch (instruction.TAG | 0) {
    case /* Nop */0 :
        return [
                line + 1 | 0,
                currVal
              ];
    case /* Acc */1 :
        return [
                line + 1 | 0,
                currVal + instruction._0 | 0
              ];
    case /* Jmp */2 :
        return [
                line + instruction._0 | 0,
                currVal
              ];
    
  }
}

function nextState(current) {
  var incCount = function (insts, line) {
    return Belt_Array.mapWithIndex(insts, (function (i, state) {
                  if (i === line) {
                    return {
                            inst: state.inst,
                            count: state.count + 1 | 0
                          };
                  } else {
                    return state;
                  }
                }));
  };
  var mapNext = function (param) {
    var value = param.value;
    var line = param.line;
    var insts = param.insts;
    return Belt_Option.map(Belt_Option.map(Belt_Array.get(insts, line), (function (param) {
                      return nextInstruction(param.inst, line, value);
                    })), (function (param) {
                  return {
                          insts: incCount(insts, line),
                          line: param[0],
                          value: param[1]
                        };
                }));
  };
  return Belt_Option.flatMap(current, mapNext);
}

function initialize(insts) {
  var i = Belt_Array.map(insts, (function (i) {
          return {
                  inst: i,
                  count: 0
                };
        }));
  return {
          insts: i,
          line: 0,
          value: 0
        };
}

var initialState = initialize(Belt_Array.keepMap(Fs.readFileSync("res/day8.txt", "utf8").split("\n"), parseLine));

function getFirstCycle(currentState) {
  var next = nextState(currentState);
  return Belt_Option.flatMap(next, (function (param) {
                if (Belt_Array.some(param.insts, (function (param) {
                          return param.count === 2;
                        }))) {
                  return currentState;
                } else {
                  return getFirstCycle(next);
                }
              }));
}

function getFirstCycleMoment(current) {
  var _current = current;
  while(true) {
    var current$1 = _current;
    var next = nextState(current$1);
    if (next === undefined) {
      return [
              current$1,
              undefined
            ];
    }
    if (Belt_Array.some(next.insts, (function (param) {
              return param.count === 2;
            }))) {
      return [
              current$1,
              next
            ];
    }
    _current = next;
    continue ;
  };
}

function findNoLoopRun(_current) {
  while(true) {
    var current = _current;
    var changeAccumulation = function (state) {
      var line = state.line;
      return {
              insts: Belt_Array.mapWithIndex(state.insts, (function (i, acc) {
                      var count = acc.count;
                      var inst = acc.inst;
                      var match = i === line;
                      if (!match) {
                        return acc;
                      }
                      switch (inst.TAG | 0) {
                        case /* Nop */0 :
                            return {
                                    inst: {
                                      TAG: /* Jmp */2,
                                      _0: inst._0
                                    },
                                    count: count
                                  };
                        case /* Acc */1 :
                            return acc;
                        case /* Jmp */2 :
                            return {
                                    inst: {
                                      TAG: /* Nop */0,
                                      _0: inst._0
                                    },
                                    count: count
                                  };
                        
                      }
                    })),
              line: state.line,
              value: state.value
            };
    };
    var match = getFirstCycleMoment(Belt_Option.map(current, changeAccumulation));
    if (match[1] === undefined) {
      return match[0];
    }
    _current = nextState(current);
    continue ;
  };
}

var first = Belt_Option.forEach(getFirstCycle(initialState), (function (x) {
        console.log(x);
        console.log(x.value);
        
      }));

console.log(findNoLoopRun(initialState));

var second;

exports.getInstruction = getInstruction;
exports.parseLine = parseLine;
exports.nextInstruction = nextInstruction;
exports.nextState = nextState;
exports.initialize = initialize;
exports.initialState = initialState;
exports.getFirstCycle = getFirstCycle;
exports.getFirstCycleMoment = getFirstCycleMoment;
exports.findNoLoopRun = findNoLoopRun;
exports.first = first;
exports.second = second;
/* initialState Not a pure module */
