// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Util = require("./Util.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Float = require("bs-platform/lib/js/belt_Float.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function sumOfTwoNotExists(param) {
  var n = param.n;
  var guard = function (x, y) {
    if (x + y === n) {
      return x !== y;
    } else {
      return false;
    }
  };
  var FloatFindable = {
    guard: guard
  };
  var FloatTwoCombFinder = Util.MakeTwoCombsFinder(FloatFindable);
  return Curry._1(FloatTwoCombFinder.find, param.previous).length === 0;
}

function initialize(arr, preamble) {
  var a = Belt_Array.keepMap(arr, Belt_Float.fromString);
  return Belt_Array.mapWithIndex(Belt_Array.keepWithIndex(a, (function (param, i) {
                    return preamble <= i;
                  })), (function (i, x) {
                return {
                        n: x,
                        previous: Belt_Array.slice(a, i - preamble | 0, preamble)
                      };
              }));
}

var inputs = Fs.readFileSync("res/day9.txt", "utf8").split("\n");

var invalidNumber = Belt_Option.mapWithDefault(Belt_Array.getBy(initialize(inputs, 25), sumOfTwoNotExists), 0, (function (param) {
        return param.n;
      }));

function findContiguousList(allList, invalid) {
  var find = function (_queue, _numberList) {
    while(true) {
      var numberList = _numberList;
      var queue = _queue;
      var sum = Belt_List.reduce(queue, 0, (function (s, n) {
              return s + n;
            }));
      if (sum < invalidNumber) {
        var match = Belt_List.head(numberList);
        var match$1 = Belt_List.tail(numberList);
        if (match === undefined) {
          return ;
        }
        if (match$1 === undefined) {
          return ;
        }
        _numberList = match$1;
        _queue = Belt_List.add(queue, match);
        continue ;
      }
      if (invalid >= sum) {
        return queue;
      }
      var l = Belt_List.length(queue);
      return Belt_Option.flatMap(Belt_List.take(queue, l - 1 | 0), (function(numberList){
                return function (q) {
                  return find(q, numberList);
                }
                }(numberList)));
    };
  };
  return find(/* [] */0, allList);
}

function findMax(l) {
  return Belt_List.reduce(l, 0, (function (m, n) {
                if (m > n) {
                  return m;
                } else {
                  return n;
                }
              }));
}

function findMin(l) {
  return Belt_List.reduce(l, 99999999999999999999999999, (function (m, n) {
                if (m < n) {
                  return m;
                } else {
                  return n;
                }
              }));
}

console.log(Belt_Option.map(findContiguousList(Belt_List.fromArray(Belt_Array.keepMap(inputs, Belt_Float.fromString)), invalidNumber), (function (l) {
            return findMax(l) + findMin(l);
          })));

var i;

exports.sumOfTwoNotExists = sumOfTwoNotExists;
exports.initialize = initialize;
exports.inputs = inputs;
exports.invalidNumber = invalidNumber;
exports.findContiguousList = findContiguousList;
exports.findMax = findMax;
exports.findMin = findMin;
exports.i = i;
/* inputs Not a pure module */
