// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");

var myPromise = new Promise((function (resolve, reject) {
        var n = 2;
        if (n !== undefined) {
          return resolve(n);
        } else {
          return reject(Js_exn.raiseError("error"));
        }
      }));

var __x = myPromise.then(function (value) {
      console.log(value);
      return Promise.resolve(value + 2 | 0);
    });

var __x$1 = __x.then(function (value) {
      console.log(value);
      return Promise.resolve(value + 3 | 0);
    });

__x$1.catch(function (err) {
      console.log("Failure!!", err);
      return Promise.resolve(-2);
    });

exports.myPromise = myPromise;
/* myPromise Not a pure module */
