// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function MakeTwoCombsFinder(Info) {
  var find = function (arr) {
    return Belt_List.toArray(Belt_Array.reduce(arr, /* [] */0, (function (l, a) {
                      return Belt_Array.reduce(arr, l, (function (l, b) {
                                    if (Curry._2(Info.guard, a, b)) {
                                      return Belt_List.add(l, [
                                                  a,
                                                  b
                                                ]);
                                    } else {
                                      return l;
                                    }
                                  }));
                    })));
  };
  return {
          find: find
        };
}

console.log(Belt_Array.concatMany([
          [
            1,
            2,
            3
          ],
          [
            4,
            5,
            6
          ]
        ]));

exports.MakeTwoCombsFinder = MakeTwoCombsFinder;
/*  Not a pure module */
